title: Gilded Rose Kata
description: Documentation site for the Gilded Rose Kata.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Iván Fernández: https://ibanfr.github.io/
  View on GitHub: https://github.com/ibanFR/gilded-rose-refactoring-kata
  
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"

